baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Schedule I Modding Wiki'
enableGitInfo = true

[module]
    # using a replacement to utilize submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]
  author = "k0"
  email = "21180271+k073l@users.noreply.github.com"
  version = "v1.0.0-wip"
  keywords = ["hugo", "doks", "documentation", "schedule I", "modding", "wiki", "schedule-I", "schedule-one"]

  [params.docs]
    themeColor = "green"
    darkMode = true
    sidebarIcons = true
    repoURL = "https://github.com/s1modding/s1modding.github.io"
    repoBranch = "main"
    editPage = true
    lastMod = true

  [params.social]
    github = "s1modding/s1modding.github.io"
    discord = "UD4K4chKak"
  
  [params.footer]
    copyright = "by Schedule I Modding Wiki contributors"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
  unsafe = true
